# Invetário refernte ao ambinte QA
running_localhost:
  hosts:
    localhost:
  vars:
    ansible_connection: local
# Lista usuários iniciais, a execução é local por KUBECTL       
    rbac_groups:
      devops-admins:
        - joaon
        - josep
        - myano
      devops-deploy:
        - devops-deploy-azure
      devops-support:
        - miguel
        - salvaro           
      devops-readonly:
         - dev
# Servers HAPROXY  
haproxy:
  hosts:
    haproxy-qa-1:
      ansible_host: 10.41.12.118 
    haproxy-qa-2:
      ansible_host: 10.41.12.119 
  vars:
    servers_k8s: false              
    port_http: 80
    port_https: 443
    port_stats_haproxy: 1936
# Conditionals Flags -> HAPROXY 
    ctrl_flags:
      is_haproxy: true 
      is_keepalived: true
      is_server: true
# Variáveis do sistema operacional SYSCTL -> HAPROXY       
    sysctl_vars:
      net.core.somaxconn: 2048  
      net.core.netdev_max_backlog: 1000    

#  Servers KUBERNETES 
# Master
master_k8s:
  hosts:       
    ctrplane-qa-1:
      ansible_host: 10.41.12.107
  vars:
# Conditionals Flags -> K8S-MASTER   
    ctrl_flags:
      is_k8s_server: true
      in_k8s_master: true
# Variáveis do sistema operacional SYSCTL -> CONTROLPLANES       
    sysctl_vars:
      net.core.somaxconn: 2048  
      net.core.netdev_max_backlog: 1000

# ControlPlanes
controlplanes:
  hosts:       
    ctrplane-qa-2:
      ansible_host: 10.41.12.108
    ctrplane-qa-3:
      ansible_host: 10.41.12.109
  vars:
# Conditionals Flags -> K8S-CONTROLPLANES    
    ctrl_flags:
      is_k8s_server: true
      in_k8s_ctrl_planel: true
# Variáveis do sistema operacional SYSCTL -> K8S-CONTROLPLANES             
    sysctl_vars:
      net.core.somaxconn: 2048  
      net.core.netdev_max_backlog: 1000    

# Workers         
workers:
  hosts:
    worker-qa-1:
      ansible_host: 10.41.12.110
    worker-qa-2:
      ansible_host: 10.41.12.111
    worker-qa-3:
      ansible_host: 10.41.12.112
  vars:
# Conditionals Flags -> K8S-WORKERS    
    ctrl_flags:
      is_k8s_server: true 
      is_k8s_workers: true
      in_k8s_workers: true
# # Variáveis do sistema operacional SYSCTL -> WORKERS    
    sysctl_vars:
      net.core.somaxconn: 6144  
      net.core.netdev_max_backlog: 20000  

# Servers OPENSEARCH 
opensearch:
  hosts:
    opensearch-1:
      ansible_host: 10.41.12.72 
# Servers MONGODB

mongodb:
  hosts:
    mongodb-1:
      ansible_host: 10.41.12.135 
    mongodb-2:
      ansible_host: 10.41.12.136
    mongodb-3:
      ansible_host: 10.41.12.137 
# Servers RABBITMQ

rabbitmq:
  hosts:
    rabbitmq-1:
      ansible_host: 10.41.12.132  
    rabbitmq-2:
      ansible_host: 10.41.12.133
    rabbitmq-3:
      ansible_host: 10.41.12.134
  
kubernetes:
  children:
    master_k8s:
    controlplanes:
    workers:

all:
  vars:
# Variáveis globais
    ansible_user: infra
    ansible_ssh_private_key_file: /home/francisco/.ssh/id_rsa

# Conditionals FLAGS  
    ctrl_flags:
      is_server: true
      is_k8s_server: true 
      is_k8s_workers: true
      is_haproxy: true 
      is_keepalived: true
      is_ingress: true 
      in_k8s_rbac: true
      in_k8s_master: true   
      in_k8s_workers: true 
      in_k8s_ctrl_planel: true

# Variáveis de ambiente (environment)    
    dns_server: 
    - 10.41.12.10
    cluster_name: qa_config
    environment_name: qa
    ip_virtual: 10.41.12.29
    network_pod: 10.244.0.0/16
    port_k8s: 6443

# Versões usadas    
    versions:
      version_k8s: 1.27.2-00
      runc_version: v1.1.6
      conteinerd_version: 1.7.1
      container_network_version: v1.3.0

## Variáveis de storage    
    storageclass:
      nfs_server: vhnfs01.tcp.com.br
      nfs_path: /data
      name_storage: nfs

## Ports RabbitMQ
    port_rabbitmq: 5672
    port_rabbitmq_http: 15672
    
  children:
    kubernetes:
    haproxy:
    opensearch:
    mongodb:
    rabbitmq: