# Invetário refernte ao ambinte QA
haproxy:
  hosts:
    haproxy-goharbor-1:
      ansible_host: 10.41.13.212 
controlplanes:
  hosts:       
    ctrplane-interno-1:
      ansible_host: 10.41.13.213
workers:
  hosts:
    worker-prd-1:
      ansible_host: 10.41.13.214
opensearch:
  hosts:
    opensearch-dash-1:
      ansible_host: 10.41.12.227
all:
  vars:
# Variáveis globais
    ansible_user: infra
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
#    ansible_ssh_pass: {{ QA-AnsiblePass }}
  children:
    kubernetes:
    haproxy_k8s:
    haproxy_app:
    opensearch:
    mongodb:
    rabbitmq:
    redis:
    consul: