{
 "title": "Kubernetes / Networking",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Network Observability Metrics\n\nUse this dashboard to visualise metrics from the Network Observability add-on for AKS. Dashboard displays metrics from Linux and Windows Clusters. To hide the irrelevant metrics, simply collapse the unwanted sections. Alternatively, you can edit the dashboard to delete unwanted panels. For any questions or issues, please see [our documentation](https://aka.ms/NetObsAddonDoc)."
   }
  },
  { "title": "Fleet View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Current Traffic by Cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (\r\n    rate(networkobservability_forward_bytes[$__rate_interval])\r\n    or\r\n    rate(kappie_forward_bytes[$__rate_interval])\r\n    or\r\n    rate(cilium_forward_bytes_total[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Forwarded by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(cluster) (\r\n    rate(networkobservability_forward_count{instance=~\"$Node\"}[$__rate_interval])\r\n    or\r\n    on(cluster)\r\n        rate(kappie_forward_count{instance=~\"$Node\"}[$__rate_interval])\r\n    or\r\n    on(cluster)\r\n        rate(cilium_forward_count_total{instance=~\"$Node\"}[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Dropped Traffic by Cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster) (\r\n    rate(networkobservability_drop_bytes[$__rate_interval])\r\n    or\r\n    rate(kappie_drop_bytes[$__rate_interval])\r\n    or\r\n    rate(cilium_drop_bytes_total[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Dropped by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(networkobservability_drop_bytes[$__rate_interval]))\r\nor\r\nsum by(cluster) (rate(kappie_drop_bytes[$__rate_interval]))\r\nor\r\nsum by(cluster) (rate(cilium_drop_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Dropped By Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(networkobservability_drop_count[$__rate_interval]))\r\nor\r\nsum by(cluster) (rate(kappie_drop_count[$__rate_interval]))\r\nor\r\nsum by(cluster) (rate(cilium_drop_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traffic (on $cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_bytes_total{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Max Egress Bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_bytes_total{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Min Egress Bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_count_total{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Max Egress Packets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_count_total{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Min Egress Packets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_bytes_total{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Max Ingress Bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_bytes_total{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Min Ingress Bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_count_total{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Max Ingress Packets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_count_total{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Min Ingress Packets"
    }
   ]
  },
  {
   "title": "Egress Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_bytes{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_bytes_total{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Egress Bytes"
    }
   ]
  },
  {
   "title": "Egress Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_count_total{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Egress Packets"
    }
   ]
  },
  {
   "title": "Ingress Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_bytes{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_bytes_total{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Ingress Bytes"
    }
   ]
  },
  {
   "title": "Ingress Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_forward_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_forward_count_total{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Ingress Packets"
    }
   ]
  },
  { "title": "Drops (on $cluster)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Packets Dropped - Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_drop_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_drop_count{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_drop_count_total{direction=\"egress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Egress)"
    }
   ]
  },
  {
   "title": "Packets Dropped - Ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_drop_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_drop_count{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(cilium_drop_count_total{direction=\"ingress\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Ingress)"
    }
   ]
  },
  {
   "title": "Packets Dropped - Unknown",
   "type": "timeseries",
   "description": "Non-Cilium only",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(networkobservability_drop_count{direction=\"unknown\", instance=~\"$Node\", cluster=\"$cluster\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_drop_count{direction=\"unknown\", instance=~\"$Node\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Unknown)"
    }
   ]
  },
  {
   "title": "Bytes Dropped by Reason",
   "type": "timeseries",
   "description": "Values:\n- Non-Cilium (Linux):\n  - iptable_rule_drop: packet dropped in iptables, e.g., because of a NetworkPolicy if using --network-policy=azure\n  - iptable_nat_drop: packet dropped in iptables during NAT (Network Address Translation)\n  - tcp_connect_basic: packet dropped by tcp connect\n  - tcp_accept_basic: packet dropped by tcp accept\n  - tcp_close_basic: packet dropped by tcp close\n  - conntrack_add_drop: packet dropped while conntrack (connection tracking) was adding the connection\n- Cilium (Linux):\n  - Many possible values",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (reason) (rate(networkobservability_drop_bytes{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (reason) (rate(kappie_drop_bytes{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (reason) (rate(cilium_drop_bytes_total{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Dropped by Reason",
   "type": "timeseries",
   "description": "Values:\n- Non-Cilium (Linux):\n  - iptable_rule_drop: packet dropped in iptables, e.g., because of a NetworkPolicy if using --network-policy=azure\n  - iptable_nat_drop: packet dropped in iptables during NAT (Network Address Translation)\n  - tcp_connect_basic: packet dropped by tcp connect\n  - tcp_accept_basic: packet dropped by tcp accept\n  - tcp_close_basic: packet dropped by tcp close\n  - conntrack_add_drop: packet dropped while conntrack (connection tracking) was adding the connection\n  - rx_dropped: an interface dropped a received packet\n  - tx_dropped: an interface dropped a transmitted packet\n- Non-Cilium (Windows):\n  - aclrule: dropped by an ACL rule in VFP, e.g., because of a NetworkPolicy\n  - endpoint: dropped by an HNS Pod Endpoint \n- Cilium (Linux):\n  - Many possible values",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (reason) (rate(networkobservability_drop_count{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (reason) (rate(kappie_drop_count{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (reason) (rate(cilium_drop_count_total{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (reason) (\r\n  label_replace(\r\n    rate(networkobservability_interface_stats{statistic_name=\"rx_dropped\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]),\r\n    \"reason\",\r\n    \"$1\",\r\n    \"statistic_name\",\r\n    \"(.*)\"\r\n  )\r\n)\r\nor # cannot combine these interface_stats expressions into one using regex, since regex would capture anything with rx_dropped or tx_dropped in it\r\nsum by (reason) (\r\n  label_replace(\r\n    rate(networkobservability_interface_stats{statistic_name=\"tx_dropped\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]),\r\n    \"reason\",\r\n    \"$1\",\r\n    \"statistic_name\",\r\n    \"(.*)\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Dropped by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(networkobservability_drop_bytes{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by(instance) (rate(kappie_drop_bytes{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by(instance) (rate(cilium_drop_bytes_total{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Dropped by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(networkobservability_drop_count{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by(instance) (rate(kappie_drop_count{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by(instance) (rate(cilium_drop_count_total{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections (on $cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Active Connections by State",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum by(state) (networkobservability_tcp_state{cluster=\"$cluster\", instance=~\"$Node\"})\r\nor\r\nsum by(state) (kappie_tcp_state{cluster=\"$cluster\", instance=~\"$Node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Active Connections by Remote Addr",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "sum by(address) (networkobservability_tcp_connection_remote{cluster=\"$cluster\", instance=~\"$Node\", address!~\"127.0.0.1|0.0.0.0\"})\r\nor\r\nsum by(address) (kappie_tcp_connection_remote{cluster=\"$cluster\", instance=~\"$Node\", address!~\"127.0.0.1|0.0.0.0\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Connection Timeouts",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_connection_stats{statistic_name=\"tcptimeouts\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_tcp_connection_stats{statistic_name=\"tcptimeouts\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
       "legendFormat": "TCP Timeouts"
      }
     ]
    },
    {
     "title": "TCP Connection Resets",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 63 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_connection_stats{statistic_name=\"resetcount\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_tcp_connection_stats{statistic_name=\"resetcount\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
       "legendFormat": "TCP Resets"
      }
     ]
    },
    {
     "title": "TCP Connection Reorders",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 63 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_connection_stats{statistic_name=\"tcptsreorder\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_tcp_connection_stats{statistic_name=\"tcptsreorder\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
       "legendFormat": "TCP Reorders"
      }
     ]
    },
    {
     "title": "TCP Flags (Windows)",
     "type": "timeseries",
     "description": "Windows Non-Cilium only",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_flag_counters{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_tcp_flag_counters{cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
       "legendFormat": "Flag Set Packets"
      }
     ]
    },
    {
     "title": "TCP Flags - RST (Windows)",
     "type": "timeseries",
     "description": "Windows Non-Cilium only",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_flag_counters{flag=\"rst\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_tcp_flag_counters{flag=\"rst\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
       "legendFormat": "TCP Reset Packets"
      }
     ]
    },
    {
     "title": "TCP Flags - SYNACK (Windows)",
     "type": "timeseries",
     "description": "Windows Non-Cilium only",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
     "targets": [
      {
       "expr": "sum(rate(networkobservability_tcp_flag_counters{flag=\"synack\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum(rate(kappie_tcp_flag_counters{flag=\"synack\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
       "legendFormat": "TCP SYNACK packets"
      }
     ]
    },
    {
     "title": "UDP Connections",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "sum(networkobservability_udp_connection_stats{statistic_name=\"active\", cluster=\"$cluster\", instance=~\"$Node\"})\r\nor\r\nsum(kappie_udp_connection_stats{statistic_name=\"active\", cluster=\"$cluster\", instance=~\"$Node\"})",
       "legendFormat": "Total UDP Connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces/Nodes (on $cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX Packets by Interface",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (interface_name) (rate(networkobservability_interface_stats{statistic_name=\"rx_packets\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum by (interface_name) (rate(kappie_interface_stats{statistic_name=\"rx_packets\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
       "legendFormat": "{{interface_name}}"
      }
     ]
    },
    {
     "title": "TX Packets by Interface",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (interface_name) (rate(networkobservability_interface_stats{statistic_name=\"tx_packets\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))\r\nor\r\nsum by (interface_name) (rate(kappie_interface_stats{statistic_name=\"tx_packets\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rx Cache Full error",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=~\"rx[0-9]+_cache_full\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (instance) (rate(kappie_interface_stats{statistic_name=~\"rx[0-9]+_cache_full\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0",
       "legendFormat": "Rx Cache full errors"
      }
     ]
    },
    {
     "title": "Tx No Op Errors",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=~\"tx[0-9]+_nop\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (instance) (rate(kappie_interface_stats{statistic_name=~\"tx[0-9]+_nop\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0",
       "legendFormat": "TX No Op, {{interface_name}}"
      }
     ]
    },
    {
     "title": "Dropped Rx Packets",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=\"rx_dropped\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dropped Tx Packets",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=\"tx_dropped\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rx Comp Full Errors",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=\"rx_comp_full\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (instance) (rate(kappie_interface_stats{statistic_name=\"rx_comp_full\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tx Send Full Errors",
     "type": "timeseries",
     "description": "Non-Cilium only",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(networkobservability_interface_stats{statistic_name=\"tx_send_full\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0\r\nor\r\nsum by (instance) (rate(kappie_interface_stats{statistic_name=\"tx_send_full\", cluster=\"$cluster\", instance=~\"$Node\"}[$__rate_interval])) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}