apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    pkgs.k8s.io/component: grafana
    pkgs.k8s.io/name: grafana
    pkgs.k8s.io/part-of: kube-prometheus
    pkgs.k8s.io/version: 10.3.1
  name: grafana
  namespace: monitoring
