# Invetário refernte ao ambinte QA
running_localhost:
  hosts:
    localhost:
  vars:
    ansible_connection: local
# Lista usuários iniciais, a execução é local por KUBECTL       
    rbac_groups:
      devops-admins:
        - joaon
        - josep
        - myano
        - gmarcelo 
      devops-deploy:
        - devops-deploy-azure
      devops-support:
        - miguel
        - salvaro           
      devops-readonly:
         - dev
# Servers HAPROXY  
haproxy_k8s:
  hosts:
    haproxy-ctos-1:
      ansible_host: 10.41.12.20
  vars:
    single_node: true 
    servers_k8s: false              
    port_http: 80
    port_https: 443
    port_stats_haproxy: 1936
# Conditionals Flags -> HAPROXY 
    ctrl_flags:
      is_haproxy: true 
      is_keepalived: true
      is_server: true
# Variáveis do sistema operacional SYSCTL -> HAPROXY       
    sysctl_vars:
      net.core.somaxconn: 2048  
      net.core.netdev_max_backlog: 1000    
# Servers HAPROXY  
haproxy_app:
  hosts:
    app-haproxy-ctos-1:
      ansible_host: 10.41.12.14 
  vars:
    single_node: true 
    servers_k8s: false              
    port_http: 80
    port_https: 443
    port_stats_haproxy: 1936
    port_redis: "6379"
    domain_rabbitmq: rabbitmq-ctosdev.tcp.com.br
    domain_redis: redis-ctosdev.tcp.com.br 
    domain_consul: consul-ctosdev.tcp.com.br
    domain_mongodb: mongodb-ctosdev.tcp.com.br  
    domain_grafana: grafana-ctosdev.tcp.com.br
# Conditionals Flags -> HAPROXY 
    ctrl_flags:
      is_haproxy: true 
      is_keepalived: true
      is_server: true
# Variáveis do sistema operacional SYSCTL -> HAPROXY       
    sysctl_vars:
      net.core.somaxconn: 2048  
      net.core.netdev_max_backlog: 1000 
# Servers KUBERNETES 
# Master
master_k8s:
  hosts:       
    ctrplane-ctos2-1:
      ansible_host: 10.41.12.74
  vars:
# Conditionals Flags -> K8S-MASTER   
    ctrl_flags:
      is_k8s_server: true
      in_k8s_master: true
# Variáveis do sistema operacional SYSCTL -> CONTROLPLANES       
    sysctl_vars:
        net.ipv4.tcp_fin_timeout: 30
        net.ipv4.tcp_tw_recycle: 1
        net.ipv4.tcp_tw_reuse: 1
        net.core.rmem_default: 524288
        net.core.wmem_default: 524288
        net.core.wmem_max: 67108864
        net.core.rmem_max: 67108864
        net.ipv4.tcp_rmem: 4096 87380 16777216
        net.ipv4.tcp_wmem: 4096 87380 16777216
        net.ipv4.ip_local_port_range: 1024 65535
        fs.file-max: 2097152
# Workers         
workers:
  hosts:
    worker-ctos-1:
      ansible_host: 10.41.12.75
    worker-ctos-2:
      ansible_host: 10.41.12.76
    worker-ctos-3:
      ansible_host: 10.41.12.77
    worker-ctos-4:
      ansible_host: 10.41.12.78
  vars:
# Conditionals Flags -> K8S-WORKERS    
    ctrl_flags:
      is_k8s_server: true 
      is_k8s_workers: true
      in_k8s_workers: true
# Variáveis do sistema operacional SYSCTL -> WORKERS    
    sysctl_vars:
        net.ipv4.tcp_fin_timeout: 30
        net.ipv4.tcp_tw_recycle: 1
        net.ipv4.tcp_tw_reuse: 1
        net.core.rmem_default: 524288
        net.core.wmem_default: 524288
        net.core.wmem_max: 67108864
        net.core.rmem_max: 67108864
        net.ipv4.tcp_rmem: 4096 87380 16777216
        net.ipv4.tcp_wmem: 4096 87380 16777216
        net.ipv4.ip_local_port_range: 1024 65535
        fs.file-max: 2097152
        vm.overcommit_memory: 2
# Servers OPENSEARCH 
opensearch:
  hosts:
    opensearch-data-1:
      ansible_host: 10.41.12.16
    opensearch-dash-coord:
       ansible_host: 10.41.12.16
  vars:
    single_node: true 
    opensearch_vars:
      disk_attached: /dev/sdb # Partição do Linux onde será motado os dados do serviço
      format_disk_atached: /dev/sdb1
      opensearch_data: /opensearch # Caminho físico onde ficará os dados do serviço OpenSearch
      version_open: 2.9.0
      version_dash: 2.9.0
      version_java: 17.0.8
      port_dashboard: 5601
      port_opensearch: 9200
      path_dash_crt: /etc/ssl/tls/tcp.com.br.crt
      path_dash_rsa: /etc/ssl/tls/tcp.com.br.rsa
      domain_name: tcp.com.br
      os_home: /etc/opensearch/
      path_certs: /etc/opensearch/certs
      os_plugin_bin_path: /opt/opensearch/bin/opensearch-plugin
      os_sec_plugin_conf_path: /opt/opensearch/config/opensearch-security
      os_sec_plugin_tools_path: /opt/opensearch/plugins/opensearch-security/tools
      os_api_port: 9200
      user_opensearch: devops-admins
    nodes:
      node-data-1: 10.41.12.16
      node-cluster_manager: 10.41.12.16
      node-coordinating:  10.41.12.16
# Conditionals Flags -> OPENSEARCH    
    ctrl_flags:
# Variáveis do sistema operacional SYSCTL -> OPENSEARCH    
    sysctl_vars:
      vm.max_map_count: 262144         
# Servers MONGODB
mongodb:
  hosts:
    mongodb-ctosdev-1:
      ansible_host: 10.41.12.15 

# Servers RABBITMQ
rabbitmq:
  hosts:
    rabbitmq-ctosdev-1:
      ansible_host: 10.41.12.18
  vars:
    server_master: true
    single_node: true
    hv_net_ife: ens160
    ctrl_flags:
      rabbit_primary: true
    sysctl_vars:
      net.ipv4.ip_nonlocal_bind: 1
      net.ipv4.tcp_window_scaling: 1
      net.core.rmem_max: 16777216
      net.core.wmem_max: 16777216
      net.ipv4.tcp_rmem: 4096 87380 16777216
      net.ipv4.tcp_wmem: 4096 65536 16777216
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_fin_timeout: 15
      net.ipv4.tcp_synack_retries: 2
      net.ipv4.tcp_max_syn_backlog: 2048
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_max_tw_buckets: 360000
# Server list Redis ambiente de QA 
redis:
  hosts:
    redis-ctosdev:
      ansible_host: 10.41.12.19
  vars:
    single_node: true 
    hv_net_ife: ens160
    port_redis: "6379"
    value_cluster_timeout: 1500 
    cluster_config_file: nodes.conf
    cluster_enabled: "yes"
    protected_mode: "no" 
    appendonly: "yes"
    cluster_require_full_coverage: "no"
    ctrl_flags:
      redis_server: true
    sysctl_vars:
      net.core.somaxconn: 65535  
      vm.overcommit_memory: 1
# Fim das configs do Redis 
kubernetes:
  children:
    master_k8s:
    controlplanes:
    workers:
all:
  vars:
# Variáveis globais
    ansible_user: infra
    ansible_ssh_private_key_file: /home/francisco/.ssh/id_rsa
#    ansible_ssh_pass: {{ QA-AnsiblePass }}
    vault:
      name: SavedCredentials
      fluentbit:
        user: QA-FluentBitUser
        pass: QA-FluentBitPass
      redis:
        pass: QA-RedisPass
# Conditionals FLAGS  
    ctrl_flags:
      is_server: true
      is_k8s_server: true 
      is_k8s_workers: true
      is_haproxy: true 
      is_keepalived: true
      is_ingress: true 
      in_k8s_rbac: true
      in_k8s_master: true   
      in_k8s_workers: true 
      in_k8s_ctrl_planel: true
# Domains usados      
    vars_domains:
      domain_rabbitmq: rabbitmq-ctosdev.tcp.com.br
      domain_redis: redis-ctosdev.tcp.com.br 
      domain_consul: consul-ctosdev.tcp.com.br
      domain_mongodb: mongodb-ctosdev.tcp.com.br  
      domain_grafana: grafana-ctosdev.tcp.com.br
# Conditionals FLAGS Kubelet
    vars_kubelet:
      evictionSoftGracePeriod:
        memory.available: 1m30s
        nodefs.available: 1m
        imagefs.available: 1m
        nodefs.inodesFree: 1m
        imagefs.inodesFree: 1m
      evictionSoft:
        memory.available: 500Mi
        nodefs.available: 10%
        imagefs.available: 10%
        nodefs.inodesFree: 10%
        imagefs.inodesFree: 10%
# Ports Aplicações 
    port_rabbitmq: "5672"
    port_rabbitmq_http: "15672"
    port_consul: "8500"
    port_redis: "6379"
    port_stats_haproxy: "1936"
    port_mongodb: "27017"

# Variáveis de ambiente (environment)    
    dns_server: 
    - 10.41.12.10
    cluster_name: ctos-dev_config
    environment_name: ctosdev
    ip_virtual: 10.41.12.20
    ip_virtual_app: 10.41.12.14
    network_pod: 10.244.0.0/16
    port_k8s: 6443
# Versões usadas    
    versions:
      version_k8s: 1.27
      runc_version: v1.1.6
      conteinerd_version: 1.7.1
      container_network_version: v1.3.0
# Variáveis de ambiente para que o RabbitMQ precisa
    rabbitmq:
      soft_nofile: 64000
      hard_nofile: 6400
# # Variáveis de storage    
    storageclass:
      nfs_server:  10.41.12.13
      nfs_path: /k8sdata/ctosdev
      name_storage: nfs
      location_storage: Oracle  
# /k8sdata *(rw)
  children:
    haproxy_k8s:
    kubernetes:
    haproxy_app:
    mongodb:
    rabbitmq:
    redis:    
    opensearch:
